### ISSUE TITLE
[BUG] Visibilità delle Particelle

### ISSUE THREAD

**Issue by GuardiaHTML** [DevLan-Support/arvan#10]
**Luogo:**

- Indeterminato (Minecraft Version 1.16.3)

**Orario e Data:**

- 25/10/2020 (Orario: informazione non presente) 

**Funzione:**

1. Possedere il ruolo "moderatore" all'interno del server (non confermato per altri ruoli) 
2. Abilitare la "creative mode" tramite la chat 
3. Inserire nel proprio personaggio delle Particelle "decorative"
4. Utilizzare il comando F3 per cambiare prospettiva (visuale in terza persona) 
5. Utilizzare un comando o una pozione per rendersi invisibile 
6. Osservare 

**Risultato Attuale:**

- A differenza del personaggio, le Particelle rimangono visibili 

**Aspettative:**

-  Rendere invisibili le Particelle, insieme al PG del giocatore 

**Informazioni Aggiuntive:**

-  Segnalazione dello STAFF: **Fargus**

**Allegato:**

- Non Disponibile

**Comment by Fargus5** [comment]
Fixed
